title: CM2005
description: Course materials, labs, and project guides for CM2005
remote_theme: just-the-docs/just-the-docs
baseurl: "/uol-oop"
url: "https://junhua.me"

# Theme settings
color_scheme: light
search_enabled: true
heading_anchors: true

# External links
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/junhua/UOL-OOP

# Enable copy code button
enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2025 Junhua Liu"

# Collections for better organization
collections:
  tutorials:
    permalink: "/:collection/:path/"
    output: true
  labs:
    permalink: "/:collection/:path/"
    output: true
  projects:
    permalink: "/:collection/:path/"
    output: true

# Navigation structure
nav:
  - title: Tutorials
    url: /tutorials/
    nav_order: 2
    has_children: true
  - title: Labs
    url: /labs/
    nav_order: 3
    has_children: true
  - title: Projects
    url: /projects/
    nav_order: 4
    has_children: true

# Default settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "tutorials"
      type: "tutorials"
    values:
      layout: "page"
      parent: "Tutorials"
  -
    scope:
      path: "tutorials/module*"
    values:
      parent: "Tutorials"
      grand_parent: null
  -
    scope:
      path: "tutorials/module*/part*"
    values:
      grand_parent: "Tutorials"
  -
    scope:
      path: "labs"
      type: "labs"
    values:
      layout: "page"
      parent: "Labs"
  -
    scope:
      path: "labs/topic*"
    values:
      parent: "Labs"
      grand_parent: null
  -
    scope:
      path: "projects"
      type: "projects"
    values:
      layout: "page"
      parent: "Projects"

# Exclude from processing
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
