title: CM2005 Object-Oriented Programming
description: Course materials, labs, and project guides for CM2005
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
baseurl: "/UOL-OOP"
url: "https://junhua.github.io"

# Site Settings
locale: "en-US"
search: true
search_full_content: true
repository: "junhua/UOL-OOP"

# Site Author
author:
  name: "Course Team"
  avatar: 
  bio: "Object-Oriented Programming Course Materials"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/junhua/UOL-OOP"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/junhua/UOL-OOP"

# Collections for better organization
collections:
  tutorials:
    permalink: "/:collection/:path/"
    output: true
  labs:
    permalink: "/:collection/:path/"
    output: true
  projects:
    permalink: "/:collection/:path/"
    output: true

# Default settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "tutorials"
      type: "tutorials"
    values:
      layout: "page"
      parent: "Tutorials"
  -
    scope:
      path: "labs"
      type: "labs"
    values:
      layout: "page"
      parent: "Labs"
  -
    scope:
      path: "projects"
      type: "projects"
    values:
      layout: "page"
      parent: "Projects"

# Exclude from processing
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Defaults for pages
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"

# Navigation
docs:
  - title: Course Content
    children:
      - title: "Tutorials"
        url: /tutorials/
      - title: "Labs"
        url: /labs/
      - title: "Projects"
        url: /projects/
