title: CM2005
description: Course materials, labs, and project guides for CM2005
remote_theme: just-the-docs/just-the-docs
baseurl: "/UOL-OOP"
url: "https://junhua.github.io"

# Theme settings
color_scheme: light
search_enabled: true
heading_anchors: false
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/junhua/UOL-OOP

# Enable copy code button
enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2025"

# Collections for better organization
collections:
  tutorials:
    permalink: "/:collection/:path/"
    output: true
  labs:
    permalink: "/:collection/:path/"
    output: true
  projects:
    permalink: "/:collection/:path/"
    output: true

# Default settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "tutorials"
      type: "tutorials"
    values:
      layout: "page"
      parent: "Tutorials"
  -
    scope:
      path: "labs"
      type: "labs"
    values:
      layout: "page"
      parent: "Labs"
  -
    scope:
      path: "projects"
      type: "projects"
    values:
      layout: "page"
      parent: "Projects"

# Exclude from processing
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Defaults for pages
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"

# Navigation
docs:
  - title: Course Content
    children:
      - title: "Tutorials"
        url: /tutorials/
      - title: "Labs"
        url: /labs/
      - title: "Projects"
        url: /projects/
